languageCode = "en"
languageName = "English"
weight = 1
title = "The Work In Progress"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img\yellowcircle.jpg"
  description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "The Work In Progress Podcast"
  image = "img/avatar.png"
  headline = "Listen Now!"
  bio = "A little bit about you"
   links = [
     { link = "https://open.spotify.com/show/5MN3CeXAKGwo7OF5HOuT5x/" },
     { instagram = "https://www.instagram.com/salehabaqirali/" },
   ]
